import Head from 'next/head'
import { useSession } from 'next-auth/react'
import Login from '../components/Login'
export default function Home() {

  const {data: session} = useSession()

  if (!session) return <Login/>
  return (
    <div >
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    
    </div>
  )
}
